### ISSUE TITLE
EAV Datetime field -- value selected is not saved upon add-to-cart

### ISSUE THREAD

**Issue by rdiaztushman** [dioscouri/tienda#110]
From product list view,
provide a datetime,
click add-to-cart.

Provided datetime is not actually stored in DB table

**Comment by rdiaztushman** [comment]
Issue also happens from the product detail view.

The correct submitted value exists all the way up to tiendahelpercarts::addItem, so the issue is in the $table->save() of the TiendaTableCarts object

**Comment by rdiaztushman** [comment]
Finally figured this out.  To resolve this, we need to add the ability for admins to specify what format the datetime field will be in.

**Comment by ChrisFrench** [comment]
Maybe we just use the config option for date time format? Could that work?

**Comment by rdiaztushman** [comment]
It can't be a global value because for EAV Custom Fields, you may want a different datetime format for different custom fields.  Imagine wanting both a DOB custom field and also a Time of Day custom field....

**Comment by ChrisFrench** [comment]
Oh yea damn your right you found a can of worms

**Comment by ChrisFrench** [comment]
I am not sure exactly what's going on with this but I was just thinking we
should if we are not already store it as a Unix time stamp and just have a
formatting option

**Comment by rdiaztushman** [comment]
Unfortunately, because of the way the EAV values are stored (they get sharded into different database tables based on their type) we can't do that.  I'm thinking of creating a new EAV type for "Time".

Looking back on this, I wish that we had used just ONE database table to store all the values for the custom fields, rather than separating them based on type.  The value for all of them could have been stored in a TEXT field, the same as with our __config tables, and this would have made things infinitely easier to manage, search, etc...

**Comment by ChrisFrench** [comment]
Hmm the problem with this, is the longer we wait  on doing the the bigger the pain in the ass it will be for the users. 

So if you want to do this we should probably do it before we are "stable"

**Comment by Skullbock** [comment]
The reason I did that was because it was easy to search AND order on. If
you made them all text it would have been both more inefficient on large
databases and it would have been harder to search and impossible to order
upon.

I had this experience lately with zoo and zoofilter and I guarantee that I
would have preferred having different tables :-)

Daniele Rosario

Il giorno 04/nov/2012, alle ore 21:57, Rafael Diaz-Tushman <
notifications@github.com> ha scritto:

Unfortunately, because of the way the EAV values are stored (they get
sharded into different database tables based on their type) we can't do
that. I'm thinking of creating a new EAV type for "Time".

Looking back on this, I wish that we had used just ONE database table to
store all the values for the custom fields, rather than separating them
based on type. The value for all of them could have been stored in a TEXT
field, the same as with our __config tables, and this would have made
things infinitely easier to manage, search, etc...

—
Reply to this email directly or view it on
GitHubhttps://github.com/dioscouri/tienda/issues/110#issuecomment-10055324.

**Comment by ChrisFrench** [comment]
is it not possible to just update the table to use unix time stamp? we could probably add something in the diagnostics to fix the table on update?

**Comment by rdiaztushman** [comment]
I've already started on a new time table and already have added the format option.  Was easier than I thought -- I just have Fiona to play with :-)

Daniele, you're right, this is better when not using Mongo :-)

## 

Rafael Diaz-Tushman
President & CEO
Dioscouri Design
www.dioscouri.com
m. 718-644-1019

**Comment by ChrisFrench** [comment]
MONGO, I want to use mongo... for something
