### ISSUE TITLE
COUPON "USE" should be counted after checkout  instead of when input

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#111]
While testing i noticed that coupons are counted as used as soon as you put it into the cart but if you don't checkout you have to reenter it and than it won't work

**Comment by rdiaztushman** [comment]
This is still an open bug, but I'm adding a note here to clarify: the issue is that the coupon's hits are increased when the order is saved, not when the coupon is added to the cart.  However, since an order can be saved with a pre-payment status and then theoretically never be paid for, the coupon hits should only be increased when the order has been marked completed.

Simple fix.  Applying now.
