### ISSUE TITLE
Question about EAV

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#123]
it looks like EAVs are setup to  be able to add custom fields to different objects,  however right now it only have products. 

Is that because we haven't built it yet? or is it because it isn't working in joomla 2.5?

**Comment by Skullbock** [comment]
It's designed for every object but I originally implemented it just for
products since they were the most urgent. Next would be addresses IMHO

Daniele Rosario

Il giorno 07/nov/2012, alle ore 22:04, Chris French <
notifications@github.com> ha scritto:

it looks like EAVs are setup to be able to add custom fields to different
objects, however right now it only have products.

Is that because we haven't built it yet? or is it because it isn't working
in joomla 2.5?

—
Reply to this email directly or view it on
GitHubhttps://github.com/dioscouri/tienda/issues/123.

**Comment by ChrisFrench** [comment]
Thanks! I have a project  right now that needs custom profiles fields, so I will add that on, on their dime
