### ISSUE TITLE
OLD-6411: Report - Inventory Levels - Select product doesn't work

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#78]
## Description

In the Report - Inventory Levels, the Select Product selection doesn't appear to have any effect on the report content.
### #4 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.4 - Plugin Testing and Finalization
### #3 Updated by Lukas Polak 9 months ago

Target version changed from Version 0.9.0 - Major Core Fixes to Version 0.9.9 - Misc Bug Fixes and New Features

First, we need to fix #3558.

Lukas
### #2 Updated by Chris DioscouriChris Paschen. 9 months ago

Assignee set to Lukas Polak
### #1 Updated by Chris DioscouriChris Paschen. 9 months ago

Priority changed from Normal to Low

**Comment by efillman** [comment]
This bug is strange because the report plug-in has code for searching by product name commented out. Did we try to move towards the product selection drop down? This report uses the products model which does not currently have support for the filter_product_name, I can add that in or just re enable the filter_name, it seems to accomplish the same thing but I am not sure what customers have preferred in the past.

$state['filter_name'] vs $state['filter_product_name']

**Comment by rdiaztushman** [comment]
Try using filter_name, the one that already exists in the products model.  I suspect there was a reason for taking it out, but for the life of me I cannot remember.....

**Comment by efillman** [comment]
Changed to filter by name
